FROM mcr.microsoft.com/windows/servercore:20H2

LABEL maintainer "nielsvdc"

# Download Links:
ENV EXE "https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-DEV-x64-ENU.exe"
ENV BOX "https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-DEV-x64-ENU.box"
ENV CU_EXE "https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB4577194-x64.exe"

ENV sa_password="_" \
  attach_dbs="[]" \
  ACCEPT_EULA="Y" \
  sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Make install files accessible
COPY start.ps1 /
WORKDIR /

# Download and install SQL Server developer
RUN Invoke-WebRequest -Uri $env:box -OutFile SQL.box ; \
  Invoke-WebRequest -Uri $env:exe -OutFile SQL.exe ; \
  Start-Process -Wait -FilePath .\SQL.exe -ArgumentList /qs, /x:setup ; \
  .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=MSSQLSERVER /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\NETWORK SERVICE' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS /SQLBACKUPDIR='C:\SqlServer\MSSQL\Backup' /SQLUSERDBDIR='C:\SqlServer\MSSQL\DATA' /SQLUSERDBLOGDIR='C:\SqlServer\MSSQL\LOG'; \
  Remove-Item -Recurse -Force SQL.exe, SQL.box, setup

RUN Stop-Service MSSQLSERVER ; \
  Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name tcpdynamicports -Value '' ; \
  Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name tcpport -Value 1433 ; \
  Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\' -name LoginMode -value 2 ;

# Download and install cumulative update
RUN Invoke-WebRequest -Uri $env:cu_exe -OutFile CU.exe ; \
  Start-Process -Wait -FilePath .\CU.exe -ArgumentList /quiet, /IAcceptSQLServerLicenseTerms, /Action=Patch, /AllInstances ; \
  Remove-Item -Recurse -Force CU.exe

HEALTHCHECK CMD [ "sqlcmd", "-Q", "select 1" ]

# Start SQL Server, set sa password and optionaly attached databases
CMD .\start.ps1 -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
